openapi: 3.0.0
info:
  title: Air Pollution In Various Height API
  description: This API provides comparison of average air pollution between differrent
    height. Raw data provided by Thai Meteorological Department (TMD).
  version: 3.0.0
servers:
- url: http://127.0.0.1:8080/air_pollution_height/
paths:
  /heights:
    get:
      summary: Returns a list of heights.
      operationId: controller_get_height
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Height'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /heights/{heightId}:
    get:
      summary: Returns complete details of the specified height
      operationId: controller_get_height_details
      parameters:
      - name: heightId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Height'
          links:
            pm:
              operationId: controller.get_pms_in_height
              parameters:
                heightId: $response.body#/heightId
            avgPM:
              operationId: controller.get_height_pm_average
              parameters:
                heightId: $response.body#/heightId
            pm_API:
              operationId: controller.get_pm_api_in_height
              parameters:
                heightId: $response.body#/heightId
            avgPM_API:
              operationId: controller.get_height_pm_api_average
              parameters:
                heightId: $response.body#/heightId
            avgSmoke:
              operationId: controller.get_height_smoke_average
              parameters:
                heightId: $response.body#/heightId
            avgCO:
              operationId: controller.get_height_co_average
              parameters:
                heightId: $response.body#/heightId
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /heights/{heightId}/pm:
    get:
      summary: Returns a list of collected PMs for specific height.
      operationId: controller_get_pms_in_height
      parameters:
      - name: heightId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PMS7'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /heights/{heightId}/avgPM:
    get:
      summary: Returns the average collected PMs for specific height.
      operationId: controller_get_height_pm_average
      parameters:
      - name: heightId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AveragePMS7'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /heights/{heightId}/pm_api:
    get:
      summary: Returns a list of collected PMs from AQI for specific height.
      operationId: controller_get_pm_api_in_height
      parameters:
      - name: heightId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PMAPI'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /heights/{heightId}/avgPM_api:
    get:
      summary: Returns the average collected PMs from AQI for specific height.
      operationId: controller_get_height_pm_api_average
      parameters:
      - name: heightId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AveragePMAPI'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /heights/{heightId}/avgSmoke:
    get:
      summary: Returns the average collected Smoke values for specific height.
      operationId: controller_get_height_smoke_average
      parameters:
      - name: heightId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageMQ2'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /heights/{heightId}/avgCO:
    get:
      summary: Returns the average collected CO values for specific height.
      operationId: controller_get_height_co_average
      parameters:
      - name: heightId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageMQ9'
                x-content-type: application/json
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Height:
      type: object
      properties:
        heightId:
          type: integer
        zone:
          type: string
        altitude:
          type: number
      example:
        altitude: 6.027456183070403
        zone: zone
        heightId: 0
    PMS7:
      type: object
      properties:
        heightId:
          type: integer
        pm10:
          type: number
        pm25:
          type: number
      example:
        pm25: 1.4658129805029452
        pm10: 6.027456183070403
        heightId: 0
    AveragePMS7:
      type: object
      properties:
        heightId:
          type: integer
        pm10:
          type: number
        pm25:
          type: number
      example:
        pm25: 1.4658129805029452
        pm10: 6.027456183070403
        heightId: 0
    PMAPI:
      type: object
      properties:
        heightId:
          type: integer
        name:
          type: string
        pm10:
          type: number
        pm25:
          type: number
      example:
        pm25: 1.4658129805029452
        name: name
        pm10: 6.027456183070403
        heightId: 0
    AveragePMAPI:
      type: object
      properties:
        heightId:
          type: integer
        name:
          type: string
        pm10:
          type: number
        pm25:
          type: number
      example:
        pm25: 1.4658129805029452
        name: name
        pm10: 6.027456183070403
        heightId: 0
    AverageMQ2:
      type: object
      properties:
        heightId:
          type: integer
        smoke:
          type: number
      example:
        smoke: 6.027456183070403
        heightId: 0
    AverageMQ9:
      type: object
      properties:
        heightId:
          type: integer
        co:
          type: number
      example:
        heightId: 0
        co: 6.027456183070403

